DATA_PATH: 'data/'
LLM: 'starling-lm:7b-alpha-q3_K_M'
EMBEDDINGS: 'sentence-transformers/all-mpnet-base-v2'
WEAVIATE_URL: 'http://weaviate:8080'
INDEX_NAME: 'Sparrow'
CHUNK_SIZE: 1000
OLLAMA_BASE_URL: 'http://ollama:11434'
